version: '3.7'
services:
  postgres:
    image: postgres:12
    container_name: ltms-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  rest:
    container_name: ltms-rest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: [ "CMD", "psql", "-h", "postgres", "-p", "5432" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres:
    name: ltms-db
