version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: ltms-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  rest:
    container_name: ltms-rest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: always
    depends_on:
      postgres:
        condition: service_started

volumes:
  postgres:
    name: ltms-db
